# Generated by Django 2.2.5 on 2020-10-16 14:12

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0068_auto_20200723_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='contactClient1',
            field=models.TextField(blank=True, default='', help_text='Indiquez le nom, prénom, rôle, numéro de téléphone et le mail de votre contact durant la mission', verbose_name='Contact Client 1'),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='contactClient2',
            field=models.TextField(blank=True, default='', help_text='Indiquez le nom, prénom, rôle, numéro de téléphone et le mail de votre contact durant la mission', verbose_name='Contact Client 2'),
        ),
        migrations.CreateModel(
            name='experiencesAValider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missionThemis', models.BooleanField(default=True, help_text='Décochez la coche, s’il s’agit d’une mission pour le compte d’une autre société', verbose_name='Mission Thémis')),
                ('nomMission', models.CharField(help_text='Indiquez le poste occupé par le consultant lors de l’intervention ex : (Consultant BI)', max_length=300, verbose_name='Niveau d’intervention')),
                ('dateDebut', models.DateField(verbose_name='date de début de mission')),
                ('dateFin', models.DateField(blank=True, null=True, verbose_name='date de fin de mission')),
                ('employeur', models.CharField(blank=True, default='', help_text=' Dans le cas où la coche « Mission Thémis » est décochée, merci d’indiquer pour le compte de quelle société avez-vous effectué cette intervention ?', max_length=300, verbose_name='Employeur lors de l’intervention')),
                ('mandataire', models.CharField(blank=True, default='', help_text='Si vous êtes passez par un intermédiaire, merci d’indiquer le nom de la société sous-traitante (ex :Eugena)', max_length=300)),
                ('service', models.CharField(blank=True, default='', help_text='Indiquez la Direction ou le Service du client dans lequel le consultant est intervenu', max_length=300, verbose_name='Direction ou Service Client')),
                ('contactClient1', models.TextField(blank=True, default='', help_text='Indiquez le nom, prénom, rôle, numéro de téléphone et le mail de votre contact durant la mission', verbose_name='Contact Client 1')),
                ('contactClient2', models.TextField(blank=True, default='', help_text='Indiquez le nom, prénom, rôle, numéro de téléphone et le mail de votre contact durant la mission', verbose_name='Contact Client 2')),
                ('resumeIntervention', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Contexte de l’intervention')),
                ('descriptifMission', ckeditor.fields.RichTextField(blank=True, default='', help_text='Décrire l’intervention en détail', verbose_name='Descriptif de la mission')),
                ('environnementMission', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Environnement Technique')),
                ('pourcentageIntervention', models.IntegerField(blank=True, default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Pourcentage du temps passé en intervention')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collab.client')),
                ('collaborateurMission', models.ForeignKey(default='', help_text='Utilisez la liste pour rattacher le collaborateur à la mission', on_delete=django.db.models.deletion.CASCADE, to='collab.collaborateurs', verbose_name='Collaborateur')),
                ('projetDeLaMission', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='collab.projet', verbose_name='Projet de la mission')),
            ],
            options={
                'verbose_name': 'Intervention a valider par Manager',
            },
        ),
    ]
